### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by REALHaydenGaming**
- adds warning.

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]
what issues exactly?

**Comment by REALHaydenGaming** [comment]
> what issues exactly?

ShadowMario & Lunar have beef with each other, and its relating to how the source code is being used?

**Comment by MemeHoovy** [comment]
> > what issues exactly?
> 
> ShadowMario & Lunar have beef with each other, and its relating to how the source code is being used?

oh dear

**Comment by MemeHoovy** [comment]
and uh, bad news, I got banned

**Comment by REALHaydenGaming** [comment]
> 

I got blocked by him on twitter for showing him the Screenshot 2022-11-09 8 24 31 PM license

**Comment by REALHaydenGaming** [comment]
> and uh, bad news, I got banned

havent yet. I think he just sees me as general annoyance and not a threat to the Github page so.

**Comment by MemeHoovy** [comment]
well, I guess he sees me as one, and the server too

**Comment by REALHaydenGaming** [comment]
> well, I guess he sees me as one, and the server too

wanna talk about it privately on twitter.

**Comment by MemeHoovy** [comment]
> > well, I guess he sees me as one, and the server too
> 
> wanna talk about it privately on twitter.

oh, do you not have discord? twitter is fine

**Comment by REALHaydenGaming** [comment]
> > > well, I guess he sees me as one, and the server too
> > 
> > 
> > wanna talk about it privately on twitter.
> 
> oh, do you not have discord? twitter is fine

no discord cuz my parents oversee simple issues.

**Comment by MemeHoovy** [comment]
oh, well okay my twitter is https://twitter.com/meme_hoovy

**Comment by lunarcleint** [comment]
tbh i should have never insulted him

**Pull request merged**
